# Schimba PROJECT_NAME cu numele proiectului
cititor:  
        # Schimba APP_NAME1 cu numele aplicatiei
        club:
            - view_name: validare_cnp_view
              url_path_name: cnp
              template_name: cnp

            - view_name: validare_cnp_view_post
              url_path_name: cnppost
              template_name: cnppost


